### ISSUE TITLE
Implement output area for e-Entity

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-workflow-editor#2]
According to the [Specification](https://docs.google.com/document/d/1b7UdThBulCSolX-ZXe8D1pIzwZ2J5Z2FA2KHA7Kf1JU/edit#heading=h.2ewbuknycwm8)

**Comment by josauder** [comment]
The current push now supports the funcitonality displayed  in the [mockup](http://api-dev.freme-project.eu/workflow)

I think it would make sense to add jenkins support and host the current version rather than the mockup.

I will need to clean up codes tomorrow, but here is a quick overview of what has been done:
- function to use rdfQuerys rdf.databank.dump() and collect all annotations and their triples correctly. This could possiby be refactored to increase modularity and reusability.
- matchAnnotationsToString function correctly inserts annotation-tooltips in the output box, annotations are properly ordered by their and seperated beginIndex and endIndex (as discussed), although I have not yet tested this completely (all edge cases of overlapping annotation offsets).

Next steps:
- Clean up code
- Test edge cases of overlapping annotation indices
- Start on implementing other e-services and make a plan about which parts of the code can be written to be more general and reusable
