### ISSUE TITLE
e-link does not work

### ISSUE THREAD

**Issue by fsasaki** [freme-project/freme-workflow-editor#26]
I am getting an error message that the template is not working.

**Comment by jnehring** [comment]
I can reproduce the error. It is odd because sometimes the request returns status 200 - ok and sometimes it returns status 400 - bad request. Even when it returns status 200 no enrichments get displayed in the UI.

Using CURL the same request always works:

curl -X POST -d @data.txt  --header "Content-Type: application/rdf-xml" "http://api.freme-project.eu/current/e-link/documents?informat=application%2Frdf%2Bxml&outformat=rdf-xml&templateid=4476"

[data.txt](https://github.com/freme-project/freme-workflow-editor/files/304420/data.txt)

**Comment by ArneBinder** [comment]
I can not reproduce this bug. Is it fixed?

**Comment by fsasaki** [comment]
works for me now.
